# Generated by Django 5.0.1 on 2024-02-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria de productos', 'verbose_name_plural': 'categoria de los productos'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='_id',
        ),
    ]
